- text: Signature Massage + Foot Scrub + Foot Massage
  value: promo-package-1
  price: "2,588"
  duration: "2 Hours &amp; 15 Minutes"

- text: Signature Massage + Body Polish + Foot Scrub
  value: promo-package-2
  price: "3,588"
  duration: "3 Hours &amp; 15 Minutes"

- text: Body Polish + Manicure + Pedicure
  value: promo-package-3
  price: "2,588"
  duration: "2 Hours &amp; 15 Minutes"

