- text: The Essenses Signature Massage
  value: the-essenses-signature-massage
  price: "1,700"
  duration: "60 Minutes"

- text: Pevonia Body Polish
  value: pevonia-body-polish
  price: "3,000"
  duration: "60 Minutes"

- text: Body Polish with Seasalt &amp; Honey
  value: body-polish-with-seasalt-and-honey
  price: "3,000"
  duration: "60 Minutes"

- text: Mt. Mayon Hot Stone Therapy Massage
  value: mt-mayon-hot-stone-therapy-massage
  price: "3,500"
  duration: "60 Minutes"

- text: Foot Spa with Scrub
  value: foot-spa-with-scrub
  price: "1,400"
  duration: "60 Minutes"

- text: Back Massage
  value: back-massage
  price: "1,250"
  duration: "60 Minutes"

- text: Foot Massage
  value: foot-massage
  price: "850"
  duration: "60 Minutes"

- text: Head Massage
  value: head-massage
  price: "700"
  duration: "60 Minutes"

- text: Hand Massage
  value: hand-massage
  price: "700"
  duration: "60 Minutes"

- text: Manicure
  value: manicure
  price: "800"
  duration: "60 Minutes"

- text: Pedicure
  value: pedicure
  price: "850"
  duration: "60 Minutes"

- text: Hand Cleaning
  value: hand-cleaning
  price: "600"
  duration: "60 Minutes"

- text: Foot Cleaning
  value: foot-cleaning
  price: "650"
  duration: "60 Minutes"

