- text: Massage
  value: massage

- text: Facials
  value: facials

- text: Body Treatments
  value: body-treatments

- text: Spa Packages
  value: spa-packages

- text: Waxing &amp; Threading
  value: waxing-and-threading

- text: For Him
  value: for-him

- text: Makeup
  value: makeup

- text: For Teens
  value: for-teens
