- text: Advanced Settings
  url: app/settings/advanced-settings.html

- text: Booking
  url: app/settings/booking.html

- text: Company
  url: app/settings/company/

- text: Custom Forms
  url: app/settings/custom-forms/

- text: Messages
  url: app/settings/messages/

- text: Satisfaction
  url: app/settings/satisfaction/

- text: Subscription
  url: app/settings/subscription.html

