- text: Advanced Settings
  url: app/settings/advanced-settings.html

- text: Company
  url: app/settings/company/

- text: Messages
  url: app/settings/messages/

- text: Satisfaction
  url: app/settings/satisfaction.html

- text: Subscription
  url: app/settings/subscription.html

